# Generated by Django 6.0.4 on 2026-04-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_add_costo_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='alicuota_iva',
            field=models.CharField(choices=[('GENERAL', 'General (16%)'), ('REDUCIDA', 'Reducida (8%)'), ('EXENTO', 'Exento (0%)')], default='GENERAL', max_length=10),
        ),
    ]
