# Generated by Django 6.0.4 on 2026-04-21 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_add_monto_recibido_vuelto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO_USD', 'Efectivo USD'), ('EFECTIVO_BS', 'Efectivo Bs'), ('TRANSFERENCIA', 'Transferencia'), ('PAGO_MOVIL', 'Pago Móvil'), ('PUNTO_DE_VENTA', 'PdV (Tarjeta)'), ('BIOPAGO', 'Biopago'), ('MIXTO', 'Pago Mixto')], max_length=20),
        ),
    ]
