# Generated by Django 6.0.4 on 2026-04-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_add_vendedor_to_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Contador de Factura',
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='numero_factura',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
