# Generated by Django 6.0.4 on 2026-04-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_add_numero_factura_y_contador'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Contador de Control',
            },
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='alicuota_iva',
            field=models.CharField(default='GENERAL', max_length=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='base_imponible_bs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='venta',
            name='base_imponible_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='iva_bs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='venta',
            name='iva_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_exento_bs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_exento_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='numero_control',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
