# Generated by Django 6.0.4 on 2026-04-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='imprimir_ticket',
            field=models.BooleanField(default=False),
        ),
    ]
