# Generated by Django 6.0.4 on 2026-04-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_empresa_imprimir_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nombre_impresora',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
