# Generated by Django 6.0.4 on 2026-04-23 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0003_add_alicuota_iva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Fiado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_bs', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tasa_aplicada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Pago parcial'), ('PAGADO', 'Pagado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=15)),
                ('notas', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiados', to='fiados.cliente')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiados_vendidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fiado',
                'verbose_name_plural': 'Fiados',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleFiado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_usd_capturado', models.DecimalField(decimal_places=4, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_fiado', to='inventario.producto')),
                ('fiado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='fiados.fiado')),
            ],
            options={
                'verbose_name': 'Detalle de fiado',
                'verbose_name_plural': 'Detalles de fiado',
            },
        ),
        migrations.CreateModel(
            name='PagoFiado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_bs', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tasa_aplicada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO_USD', 'Efectivo USD'), ('EFECTIVO_BS', 'Efectivo Bs'), ('TRANSFERENCIA', 'Transferencia'), ('PAGO_MOVIL', 'Pago Móvil'), ('PUNTO_DE_VENTA', 'PdV (Tarjeta)'), ('BIOPAGO', 'Biopago')], max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('fiado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='fiados.fiado')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_fiado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abono',
                'verbose_name_plural': 'Abonos',
                'ordering': ['-fecha'],
            },
        ),
    ]
