# Generated by Django 6.0.4 on 2026-04-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
                ('fecha', models.DateField()),
                ('efectivo_usd_esperado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('efectivo_bs_esperado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('efectivo_usd_real', models.DecimalField(decimal_places=2, max_digits=10)),
                ('efectivo_bs_real', models.DecimalField(decimal_places=2, max_digits=14)),
                ('diferencia_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('diferencia_bs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Cierre de caja',
                'verbose_name_plural': 'Cierres de caja',
                'ordering': ['-fecha_cierre'],
                'unique_together': {('fecha',)},
            },
        ),
    ]
