# Generated by Django 6.0.4 on 2026-04-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_cierrecaja_biopago_total_cierrecaja_mixto_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecaja',
            name='abonos_bs_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='abonos_usd_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
