# Generated by Django 6.0.4 on 2026-04-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_abonos_en_cierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecaja',
            name='gran_total_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
